# Site settings
title: 
header-img: img/home-bg.png
email: hey@iamdavidmoore.com
copyright_name: iamdavidmichaelmoore
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  iamdavidmichaelmoore
learn_profile: iamdavidmichaelmoore
email_username: hey@iamdavidmoore.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
